"""
Canonical schema for the Product Intelligence pipeline.

Design notes
------------
* Zero third-party dependencies. The whole deterministic core (schema,
  extractor, normalizer, taxonomy, validator, explainer, evaluation) runs on
  the standard library alone, so it works fully offline, imports in a Celery
  worker without FastAPI, and is unit-testable without a database.
* Every derived value carries provenance. `FieldValue` records *where* a value
  came from (which rule, which span of the input text, or which LLM call) and
  *how confident* the pipeline is. Explainability is therefore a property of
  the data structure, not a prompt written after the fact.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Dict, List, Optional


class Origin(str, Enum):
    """Where a field value came from. Ordered by trustworthiness."""

    INPUT = "input"          # supplied verbatim by the user / source system
    EXTRACTED = "extracted"  # deterministic regex/parser hit on source text
    DERIVED = "derived"      # computed from other fields (e.g. current from kW/V)
    TAXONOMY = "taxonomy"    # rule-based classifier
    LLM = "llm"              # generated by the local language model
    DEFAULT = "default"      # category default, weakest evidence


#: Confidence ceiling per origin. An LLM guess can never outrank a value that
#: was literally present in the input text; this is what keeps enrichment from
#: silently overwriting ground truth.
ORIGIN_TRUST: Dict[Origin, float] = {
    Origin.INPUT: 1.00,
    Origin.EXTRACTED: 0.95,
    Origin.DERIVED: 0.85,
    Origin.TAXONOMY: 0.80,
    Origin.LLM: 0.65,
    Origin.DEFAULT: 0.30,
}


@dataclass
class Evidence:
    """A concrete, checkable reason for a value."""

    kind: str                       # "text_span" | "rule" | "llm" | "computation"
    detail: str                     # human-readable explanation
    source_text: Optional[str] = None   # the exact substring that triggered it
    span: Optional[List[int]] = None    # [start, end] offsets into source_text_field
    rule_id: Optional[str] = None       # e.g. "EXT.POWER.KW"

    def to_dict(self) -> Dict[str, Any]:
        return {k: v for k, v in asdict(self).items() if v is not None}


@dataclass
class FieldValue:
    """A single enriched field plus the full audit trail behind it."""

    value: Any
    origin: Origin
    confidence: float
    unit: Optional[str] = None
    raw: Optional[str] = None                     # pre-normalisation text
    evidence: List[Evidence] = field(default_factory=list)

    def __post_init__(self) -> None:
        ceiling = ORIGIN_TRUST[self.origin]
        self.confidence = round(max(0.0, min(self.confidence, ceiling)), 4)

    def beats(self, other: "FieldValue") -> bool:
        """Should this value replace `other`? Trust first, then confidence."""
        if other is None:
            return True
        mine, theirs = ORIGIN_TRUST[self.origin], ORIGIN_TRUST[other.origin]
        if mine != theirs:
            return mine > theirs
        return self.confidence > other.confidence

    def to_dict(self) -> Dict[str, Any]:
        out: Dict[str, Any] = {
            "value": self.value,
            "origin": self.origin.value,
            "confidence": self.confidence,
        }
        if self.unit:
            out["unit"] = self.unit
        if self.raw:
            out["raw"] = self.raw
        if self.evidence:
            out["evidence"] = [e.to_dict() for e in self.evidence]
        return out


@dataclass
class RawProduct:
    """Whatever the source system gave us. Deliberately permissive."""

    name: str
    description: str = ""
    category: str = ""
    source: str = "manual"                 # "csv" | "pdf" | "html" | "manual" | "api"
    source_ref: str = ""                   # filename, URL, row number
    attributes: Dict[str, str] = field(default_factory=dict)

    def text_blob(self) -> str:
        """Everything searchable, concatenated in a stable order."""
        parts = [self.name, self.description]
        parts += [f"{k}: {v}" for k, v in sorted(self.attributes.items())]
        return "\n".join(p for p in parts if p)

    def fingerprint(self) -> str:
        """Stable hash used for de-duplication across sources."""
        basis = f"{_squash(self.name)}|{_squash(self.category)}"
        return hashlib.sha256(basis.encode("utf-8")).hexdigest()[:16]


@dataclass
class EnrichedProduct:
    """The pipeline output: structured, scored, and fully explainable."""

    raw: RawProduct
    category: Optional[FieldValue] = None
    category_path: List[str] = field(default_factory=list)
    category_alternatives: List[Dict[str, Any]] = field(default_factory=list)
    specifications: Dict[str, FieldValue] = field(default_factory=dict)
    attributes: List[str] = field(default_factory=list)
    keywords: List[str] = field(default_factory=list)
    enriched_description: Optional[FieldValue] = None
    validation: Dict[str, Any] = field(default_factory=dict)
    explanation: Dict[str, Any] = field(default_factory=dict)
    pipeline_trace: List[Dict[str, Any]] = field(default_factory=list)

    # -- helpers ---------------------------------------------------------

    def set_spec(self, key: str, value: FieldValue) -> bool:
        """Insert a spec, keeping the better-sourced value on conflict."""
        existing = self.specifications.get(key)
        if existing is None or value.beats(existing):
            if existing is not None:
                value.evidence.append(
                    Evidence(
                        kind="rule",
                        detail=(
                            f"Overrode {existing.origin.value} value "
                            f"{existing.value!r} (conf {existing.confidence}) "
                            f"with higher-trust {value.origin.value} value"
                        ),
                        rule_id="MERGE.TRUST_ORDER",
                    )
                )
            self.specifications[key] = value
            return True
        return False

    def trace(self, stage: str, **detail: Any) -> None:
        self.pipeline_trace.append({"stage": stage, **detail})

    def completeness(self) -> float:
        """Fraction of populated fields that actually carry a value."""
        slots = 4 + len(self.specifications)  # name, desc, category, keywords
        filled = 1  # name is mandatory
        if self.enriched_description and self.enriched_description.value:
            filled += 1
        if self.category and self.category.value:
            filled += 1
        if self.keywords:
            filled += 1
        filled += sum(1 for f in self.specifications.values() if f.value not in (None, ""))
        return round(filled / slots, 4) if slots else 0.0

    def mean_confidence(self) -> float:
        vals = [f.confidence for f in self.specifications.values()]
        if self.category:
            vals.append(self.category.confidence)
        return round(sum(vals) / len(vals), 4) if vals else 0.0

    def to_dict(self, include_trace: bool = False) -> Dict[str, Any]:
        out: Dict[str, Any] = {
            "name": self.raw.name,
            "source": {"type": self.raw.source, "ref": self.raw.source_ref},
            "fingerprint": self.raw.fingerprint(),
            "category": self.category.to_dict() if self.category else None,
            "category_path": self.category_path,
            "category_alternatives": self.category_alternatives,
            "enriched_description": (
                self.enriched_description.to_dict() if self.enriched_description else None
            ),
            "specifications": {k: v.to_dict() for k, v in self.specifications.items()},
            "attributes": self.attributes,
            "keywords": self.keywords,
            "validation": self.validation,
            "explanation": self.explanation,
            "metrics": {
                "completeness": self.completeness(),
                "mean_confidence": self.mean_confidence(),
                "spec_count": len(self.specifications),
            },
        }
        if include_trace:
            out["pipeline_trace"] = self.pipeline_trace
        return out

    def to_flat_dict(self) -> Dict[str, Any]:
        """Commerce-ready flat row for CSV / catalog export."""
        row: Dict[str, Any] = {
            "name": self.raw.name,
            "category": self.category.value if self.category else "",
            "category_path": " > ".join(self.category_path),
            "description": (
                self.enriched_description.value if self.enriched_description else self.raw.description
            ),
            "keywords": ", ".join(self.keywords),
            "validation_status": self.validation.get("status", "unknown"),
            "validation_score": self.validation.get("score", 0.0),
            "completeness": self.completeness(),
        }
        for key, fv in sorted(self.specifications.items()):
            row[f"spec.{key}"] = f"{fv.value} {fv.unit}".strip() if fv.unit else fv.value
        return row


def _squash(text: str) -> str:
    """Aggressive normalisation used for fingerprinting and matching."""
    return "".join(ch for ch in text.lower() if ch.isalnum())
